### ISSUE TITLE
很扒错的作品，但是在启动的时候有一个潜藏问题

### ISSUE THREAD

**Issue by LangInteger** [Tai-Zhou/astrolator#1]
第一次扫码加载出来的时候，页面上只有长长的文字介绍在底部

无法看到任何和功能相关的东西，很奇怪

随便划一划功能界面出来之后，又无法找到最开始打开的那个感觉是 bug 的界面了

并不是每次打开都会这样，感觉只有以前从来没有使用过这小程序第一次扫码打开会出现那个问题

颇有点不可描述，能提供的信息仅止于此

**Comment by LangInteger** [comment]
Just want you to know and close it now``

**Comment by Tai-Zhou** [comment]
> 第一次扫码加载出来的时候，页面上只有长长的文字介绍在底部
> 
> 无法看到任何和功能相关的东西，很奇怪
> 
> 随便划一划功能界面出来之后，又无法找到最开始打开的那个感觉是 bug 的界面了
> 
> 并不是每次打开都会这样，感觉只有以前从来没有使用过这小程序第一次扫码打开会出现那个问题
> 
> 颇有点不可描述，能提供的信息仅止于此

谢谢您的反馈！这个页面设计上是个欢迎页（src/pages/welcome/welcome.wxml），并且仅当首次使用时弹出，从页面左侧右划即可关闭。或许之后可以在页面底部加句提示语或是一个类似“开始使用”的按钮。

**Comment by LangInteger** [comment]
原来如此，竟如此别具匠心，独具一格😋

hin 有个性了～
